# Basic info
name: けちょろぐ
domain: blog.kechol.net
url: http://blog.kechol.net
description: Just Another Tech Blog by Kechol.
author: Kazuyuki SUZUKI

# Format
markdown: redcarpet
pygments: true
encoding: UTF-8
permalink: /:year/:month/:day/:title
safe: false

# Build
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 's3_website.yml']
